#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"
work_dir=$(mktemp -d)
remote_dir=""
cleanup() {
  rm -rf "$work_dir"
  if [[ -n $remote_dir && -n ${SERVER_ADMIN_TARGET:-} ]]; then
    ssh -p "${SERVER_ADMIN_PORT:-22}" "$SERVER_ADMIN_TARGET" \
      "rm -rf '$remote_dir'" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT HUP INT TERM
umask 077

ask_default() {
  local key=$1 prompt=$2 default=$3 input=""
  printf '  %s%s%s %s[%s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$default" "$RESET"
  read -r input || true
  printf -v "$key" '%s' "${input:-$default}"
}

require_value() {
  [[ -n ${!1:-} ]] || { echo "error: $1 must not be empty" >&2; exit 1; }
}

if [[ ${1:-} == --help || ${1:-} == -h ]]; then
  echo "usage: ./scripts/provision_conan_ci.sh"
  echo "Provision or rotate restricted Conan SSH and read-only CI credentials."
  exit 0
elif [[ $# -ne 0 ]]; then
  echo "error: unexpected argument: $1" >&2
  exit 2
fi

banner "Restricted Conan CI access"

stage "Preflight and emergency revocation"
say "This wizard changes a dedicated server account, Conan authorizer, and repository Secrets."
for command in gh openssl python3 scp ssh ssh-keygen ssh-keyscan; do
  command -v "$command" >/dev/null 2>&1 || { echo "error: missing command: $command" >&2; exit 1; }
done
gh auth status >/dev/null 2>&1 || { echo "error: authenticate gh before continuing" >&2; exit 1; }
[[ -f $repo_root/conan.lock ]] || { echo "error: run from the ros-sdk checkout" >&2; exit 1; }
ask SERVER_ADMIN_TARGET "Server admin SSH target (user@host):"
require_value SERVER_ADMIN_TARGET
ask_default SERVER_ADMIN_PORT "Server admin SSH port:" "22"
[[ $SERVER_ADMIN_TARGET =~ ^[A-Za-z0-9._@:-]+$ && $SERVER_ADMIN_PORT =~ ^[0-9]+$ ]] || {
  echo "error: invalid server admin target or port" >&2
  exit 1
}
(( 10#$SERVER_ADMIN_PORT >= 1 && 10#$SERVER_ADMIN_PORT <= 65535 )) || {
  echo "error: server admin port must be between 1 and 65535" >&2
  exit 1
}
ask EMERGENCY_KEY_ID "Compromised key ID to revoke immediately (blank if none):"
if [[ -n $EMERGENCY_KEY_ID ]]; then
  [[ $EMERGENCY_KEY_ID =~ ^[A-Za-z0-9][A-Za-z0-9._:-]*$ ]] || {
    echo "error: invalid emergency key ID" >&2
    exit 1
  }
  ask_default SSH_USER "Dedicated tunnel OS user:" "rosbridge-conan-ci"
  [[ $SSH_USER =~ ^[a-z_][a-z0-9_-]*$ ]] || { echo "error: invalid SSH user" >&2; exit 1; }
  confirm "Immediately revoke $EMERGENCY_KEY_ID from $SSH_USER?" || exit 1
  scp -P "$SERVER_ADMIN_PORT" "$repo_root/scripts/ci/apply_conan_ssh_policy.sh" \
    "$SERVER_ADMIN_TARGET:/tmp/apply-conan-ssh-policy.sh" >/dev/null
  ssh -p "$SERVER_ADMIN_PORT" "$SERVER_ADMIN_TARGET" \
    "sudo bash /tmp/apply-conan-ssh-policy.sh remove '$SSH_USER' '$EMERGENCY_KEY_ID'; rm -f /tmp/apply-conan-ssh-policy.sh"
  say "The suspected key was revoked before any replacement was created."
fi

stage "Endpoint and identity"
ask_default CONAN_SSH_HOST "Public SSH host:" "106.55.24.85"
ask_default CONAN_SSH_PORT "Public SSH port:" "22"
ask_default SSH_USER "Dedicated tunnel OS user:" "rosbridge-conan-ci"
ask_default TARGET_HOST "Conan endpoint as seen by sshd:" "127.0.0.1"
ask_default TARGET_PORT "Conan endpoint port:" "9300"
package_policy=$repo_root/scripts/ci/conan_arm64_packages.json
CONAN_USERNAME=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["username"])' \
  "$package_policy")
say "Dedicated Conan reader from exact ARM64 policy: $CONAN_USERNAME"
ask OLD_KEY_ID "Old key ID to remove after successful overlap rotation (blank for first setup):"
ask_default CONAN_SERVER_CONFIG "Conan Server config path:" "/root/.conan_server/server.conf"
ask_default CONAN_SERVICE "Conan Server systemd service:" "conan-server"
[[ $CONAN_SSH_PORT =~ ^[0-9]+$ && $TARGET_PORT =~ ^[0-9]+$ ]] || {
  echo "error: ports must be numeric" >&2
  exit 1
}
(( 10#$CONAN_SSH_PORT >= 1 && 10#$CONAN_SSH_PORT <= 65535 && \
   10#$TARGET_PORT >= 1 && 10#$TARGET_PORT <= 65535 )) || {
  echo "error: ports must be between 1 and 65535" >&2
  exit 1
}
[[ $CONAN_SSH_HOST =~ ^[A-Za-z0-9][A-Za-z0-9._:-]*$ ]] || {
  echo "error: invalid public SSH host" >&2
  exit 1
}
if [[ -n $OLD_KEY_ID && ! $OLD_KEY_ID =~ ^[A-Za-z0-9][A-Za-z0-9._:-]*$ ]]; then
  echo "error: invalid old key ID" >&2
  exit 1
fi
[[ $CONAN_SERVER_CONFIG =~ ^/[A-Za-z0-9._/-]+$ && $CONAN_SERVICE =~ ^[A-Za-z0-9_.@-]+$ ]] || {
  echo "error: invalid server config path or service name" >&2
  exit 1
}
key_id="ros-sdk-github-actions-$(date -u +%Y-%m-%d)-$(openssl rand -hex 4)"
private_key=$work_dir/id_ed25519
ssh-keygen -q -t ed25519 -N "" -C "$key_id" -f "$private_key"
conan_password=""
if [[ -z $OLD_KEY_ID || -n $EMERGENCY_KEY_ID ]]; then
  conan_password=$(openssl rand -base64 32 | tr -d '\n')
fi
printf '%s\n' "$conan_password" > "$work_dir/conan_password"
python3 -m scripts.ci.conan_access render \
  --public-key-file "$private_key.pub" \
  --destination-host "$TARGET_HOST" \
  --destination-port "$TARGET_PORT" \
  --key-id "$key_id" \
  --ssh-user "$SSH_USER" \
  --lockfile "$repo_root/conan.lock" \
  --package-policy "$package_policy" \
  --output-directory "$work_dir/policy"
say "Generated a fresh Ed25519 identity: $key_id"

stage "Host identity"
say "Obtain the SSH host-key fingerprints independently from the server console or provider panel."
ssh-keyscan -p "$CONAN_SSH_PORT" "$CONAN_SSH_HOST" \
  > "$work_dir/known_hosts" 2>/dev/null
[[ -s $work_dir/known_hosts ]] || { echo "error: no SSH host keys received" >&2; exit 1; }
ssh-keygen -lf "$work_dir/known_hosts"
confirm "Do these fingerprints exactly match the independently verified server fingerprints?" || exit 1
say "Host verification material will be stored only as a GitHub Secret."

stage "Restricted server-side SSH policy"
remote_dir="/tmp/ros-sdk-conan-$key_id"
ssh -p "$SERVER_ADMIN_PORT" "$SERVER_ADMIN_TARGET" "mkdir -m 700 '$remote_dir'"
scp -P "$SERVER_ADMIN_PORT" \
  "$repo_root/scripts/ci/apply_conan_ssh_policy.sh" \
  "$work_dir/policy/authorized_key" \
  "$work_dir/policy/sshd_config" \
  "$SERVER_ADMIN_TARGET:$remote_dir/" >/dev/null
step "Review the generated authorized_keys and sshd Match policy shown below."
sed 's/^/  /' "$work_dir/policy/authorized_key"
sed 's/^/  /' "$work_dir/policy/sshd_config"
confirm "Install this dedicated account policy and reload sshd?" || exit 1
ssh -p "$SERVER_ADMIN_PORT" "$SERVER_ADMIN_TARGET" \
  "sudo bash '$remote_dir/apply_conan_ssh_policy.sh' install '$SSH_USER' '$key_id' '$remote_dir'"
say "The account has no login shell; sshd also denies PTY, agent/X11, remote and arbitrary forwarding."

stage "Exact read-only Conan identity"
say "A custom authorizer limits this user to exact recipe revisions and ARM64 package IDs."
say "Every other user continues through the server's existing read/write ACLs unchanged."
step "Review the exact package policy shown below."
sed 's/^/  /' "$work_dir/policy/conan_policy.json"
confirm "Install the exact-package authorizer and add the dedicated reader?" || exit 1
scp -P "$SERVER_ADMIN_PORT" \
  "$repo_root/scripts/ci/apply_conan_server_config.py" \
  "$repo_root/scripts/ci/conan_exact_reader_authorizer.py" \
  "$work_dir/policy/conan_policy.json" \
  "$work_dir/conan_password" \
  "$SERVER_ADMIN_TARGET:$remote_dir/" >/dev/null
ssh -p "$SERVER_ADMIN_PORT" "$SERVER_ADMIN_TARGET" \
  "sudo python3 '$remote_dir/apply_conan_server_config.py' --config '$CONAN_SERVER_CONFIG' --username '$CONAN_USERNAME' --password-file '$remote_dir/conan_password' --plugin '$remote_dir/conan_exact_reader_authorizer.py' --policy '$remote_dir/conan_policy.json'"
if ! ssh -p "$SERVER_ADMIN_PORT" "$SERVER_ADMIN_TARGET" \
  "sudo systemctl restart '$CONAN_SERVICE'"; then
  warn "The config is updated, but systemd could not restart the Conan service."
  pause "Restart Conan Server through its real supervisor, then press Enter."
fi
ssh -p "$SERVER_ADMIN_PORT" "$SERVER_ADMIN_TARGET" "rm -rf '$remote_dir'"
remote_dir=""

stage "Repository Secrets"
private_key_value=$(<"$private_key")
known_hosts_value=$(<"$work_dir/known_hosts")
set_secret CONAN_SSH_PRIVATE_KEY "$private_key_value"
set_secret CONAN_SSH_KNOWN_HOSTS "$known_hosts_value"
set_secret CONAN_SSH_HOST "$CONAN_SSH_HOST"
set_secret CONAN_SSH_PORT "$CONAN_SSH_PORT"
set_secret CONAN_SSH_USER "$SSH_USER"
set_secret CONAN_SSH_TARGET_HOST "$TARGET_HOST"
set_secret CONAN_SSH_TARGET_PORT "$TARGET_PORT"
set_secret CONAN_LOGIN_USERNAME "$CONAN_USERNAME"
if [[ -n $conan_password ]]; then
  set_secret CONAN_PASSWORD "$conan_password"
else
  say "Keeping the existing Conan password during overlap key rotation."
fi
rotate_after=$(python3 -c 'from datetime import date,timedelta; print(date.today()+timedelta(days=180))')
set_var CONAN_SSH_KEY_ID "$key_id"
set_var CONAN_SSH_ROTATE_AFTER "$rotate_after"
say "Secrets were streamed to GitHub CLI and will be deleted from local temporary storage on exit."
if (( ${#SKIPPED[@]} )); then
  echo "error: every repository secret and variable must be updated before smoke testing" >&2
  exit 1
fi

stage "Trusted smoke and overlap completion"
step "The workflow uses strict host checking, the restricted tunnel, Server ping/auth, and --build=never."
trusted_ref=$(gh repo view --json defaultBranchRef --jq '.defaultBranchRef.name')
[[ $trusted_ref == main ]] || { echo "error: trusted default branch must be main" >&2; exit 1; }
dispatch_nonce="provision-$key_id-$(openssl rand -hex 4)"
gh workflow run conan-access-smoke.yml --ref "$trusted_ref" -f "nonce=$dispatch_nonce"
run_id=$(python3 -m scripts.ci.conan_access wait-smoke-run \
  --workflow conan-access-smoke.yml --branch "$trusted_ref" --nonce "$dispatch_nonce")
gh run watch "$run_id" --exit-status
if [[ -n $OLD_KEY_ID ]]; then
  confirm "Smoke passed. Remove old key $OLD_KEY_ID now?" || exit 1
  scp -P "$SERVER_ADMIN_PORT" "$repo_root/scripts/ci/apply_conan_ssh_policy.sh" \
    "$SERVER_ADMIN_TARGET:/tmp/apply-conan-ssh-policy.sh" >/dev/null
  ssh -p "$SERVER_ADMIN_PORT" "$SERVER_ADMIN_TARGET" \
    "sudo bash /tmp/apply-conan-ssh-policy.sh remove '$SSH_USER' '$OLD_KEY_ID'; rm -f /tmp/apply-conan-ssh-policy.sh"
fi
say "Rotate again by $rotate_after: add new key, update Secrets, verify, then remove this key."
say "For suspected leakage, re-run and provide the compromised key ID in Stage 1 for immediate revocation."

finish
