# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'delivery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65livery.proto\x12\x11ros2_sdk.delivery\"^\n\x15\x43reateDeliveryRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x17\n\x0fpickup_location\x18\x02 \x01(\t\x12\x18\n\x10\x64ropoff_location\x18\x03 \x01(\t\"%\n\x12GetDeliveryRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\xef\x01\n\x10\x44\x65liverySnapshot\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x17\n\x0fpickup_location\x18\x03 \x01(\t\x12\x18\n\x10\x64ropoff_location\x18\x04 \x01(\t\x12/\n\x05state\x18\x05 \x01(\x0e\x32 .ros2_sdk.delivery.DeliveryState\x12\x16\n\x0e\x63urrent_target\x18\x06 \x01(\t\x12!\n\x14remaining_distance_m\x18\x07 \x01(\x01H\x00\x88\x01\x01\x42\x17\n\x15_remaining_distance_m*y\n\rDeliveryState\x12\x1e\n\x1a\x44\x45LIVERY_STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08STARTING\x10\x01\x12\x18\n\x14NAVIGATING_TO_PICKUP\x10\x02\x12 \n\x1c\x41WAITING_PICKUP_CONFIRMATION\x10\x03\x32\xcd\x01\n\x0f\x44\x65liveryService\x12_\n\x0e\x43reateDelivery\x12(.ros2_sdk.delivery.CreateDeliveryRequest\x1a#.ros2_sdk.delivery.DeliverySnapshot\x12Y\n\x0bGetDelivery\x12%.ros2_sdk.delivery.GetDeliveryRequest\x1a#.ros2_sdk.delivery.DeliverySnapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DELIVERYSTATE']._serialized_start=414
  _globals['_DELIVERYSTATE']._serialized_end=535
  _globals['_CREATEDELIVERYREQUEST']._serialized_start=37
  _globals['_CREATEDELIVERYREQUEST']._serialized_end=131
  _globals['_GETDELIVERYREQUEST']._serialized_start=133
  _globals['_GETDELIVERYREQUEST']._serialized_end=170
  _globals['_DELIVERYSNAPSHOT']._serialized_start=173
  _globals['_DELIVERYSNAPSHOT']._serialized_end=412
  _globals['_DELIVERYSERVICE']._serialized_start=538
  _globals['_DELIVERYSERVICE']._serialized_end=743
# @@protoc_insertion_point(module_scope)
