# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime_health.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'runtime_health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14runtime_health.proto\x12\x10ros2_sdk.runtime\"\x0f\n\rHealthRequest\"Q\n\x0eHealthResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x16\n\x0e\x64\x65livery_ready\x18\x02 \x01(\x08\x12\x18\n\x10readiness_reason\x18\x03 \x01(\t2]\n\x0eRuntimeService\x12K\n\x06Health\x12\x1f.ros2_sdk.runtime.HealthRequest\x1a .ros2_sdk.runtime.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime_health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=42
  _globals['_HEALTHREQUEST']._serialized_end=57
  _globals['_HEALTHRESPONSE']._serialized_start=59
  _globals['_HEALTHRESPONSE']._serialized_end=140
  _globals['_RUNTIMESERVICE']._serialized_start=142
  _globals['_RUNTIMESERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
